# -*- coding: utf-8 -*-
"""Q15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6tgU8oKEfUjzncy6-GydeaTSpD0V8gd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def main():
    df = pd.read_csv('NetflixOriginals.csv', encoding='latin-1')

    # Q15 Veri setinde outlier veri var mıdır? Açıklayınız

    # Z-Score Analysis to find outlier value

    df.info()
    # Runtime and IMDB Score columns are numerical.

    analyzed_columns = ["Runtime", "IMDB Score"]
    for column in analyzed_columns:
        sns.histplot(df[column], kde=True)
        plt.show()
        max_value = (3 * df[column].std()) + df[column].mean()
        min_value = -((3 * df[column].std()) + df[column].mean())

        new_mean = df.loc[(df[column] > min_value) & (df[column] < max_value), column].mean()

        if new_mean is not np.nan:
            print(f"There is outlier value in {column} category due to mean is {new_mean} which is not np.nan!")
        else:
            print(f"There is no outlier value in {column} category.")

